server:
  port: 9001
application:
  security:
    jwt:
      secret-key: 7Elj4DLH0MMHTWTpmQGQqJHeuBHmJbYkrqmOkkRo99gD/cCNZB/X6ak+i6jVAdks
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

 # mail:
    #     host: smtp.gmail.com
    #     #     port: 587
    #     protocol: smtps
    #     username: willypoze5@gmail.com
    #     password: Willy9470@$
      #    properties:
        #      mail:
          #        smtp:
          #         #         auth: true
    #         starttls:
    #           enable: true


support:
  email: willypoze5@gmail.com




